// Territory coverage engine for Tulsa market
// Tracks which territories have been researched per industry
// Automatically selects the next logical territory to research

export interface Territory {
  key: string
  name: string
  priority: number
  zipCodes: string[]
  bestFor: string[]
  notes: string
}

export const TULSA_TERRITORIES: Territory[] = [
  {
    key: 'midtown_tulsa',
    name: 'Midtown Tulsa',
    priority: 1,
    zipCodes: ['74104', '74105', '74114', '74135'],
    bestFor: ['dental', 'medical', 'financial', 'accounting', 'law', 'general_offices'],
    notes: 'High-density professional office market. Strong first territory.',
  },
  {
    key: 'south_tulsa',
    name: 'South Tulsa',
    priority: 2,
    zipCodes: ['74133', '74136', '74137', '74145', '74146'],
    bestFor: ['dental', 'medical', 'financial', 'accounting', 'general_offices'],
    notes: 'Strong suburban commercial market with medical, dental, financial, and office prospects.',
  },
  {
    key: 'downtown_tulsa',
    name: 'Downtown / Central Tulsa',
    priority: 3,
    zipCodes: ['74103', '74119', '74120', '74127'],
    bestFor: ['accounting', 'financial', 'law', 'general_offices', 'church'],
    notes: 'Professional firms and churches. Flag large towers where janitorial may be bundled.',
  },
  {
    key: 'east_tulsa_industrial',
    name: 'East Tulsa / Industrial Corridor',
    priority: 4,
    zipCodes: ['74108', '74112', '74115', '74116', '74128', '74129', '74134'],
    bestFor: ['industrial', 'manufacturing', 'general_offices'],
    notes: 'Industrial front offices, manufacturing, logistics, distribution, service companies.',
  },
  {
    key: 'north_west_tulsa',
    name: 'North / West Tulsa',
    priority: 5,
    zipCodes: ['74106', '74107', '74110', '74117', '74126', '74130', '74131', '74132'],
    bestFor: ['industrial', 'church', 'general_offices'],
    notes: 'Industrial, churches, service businesses, overlooked small office prospects.',
  },
  {
    key: 'broken_arrow',
    name: 'Broken Arrow',
    priority: 6,
    zipCodes: ['74011', '74012', '74013', '74014'],
    bestFor: ['dental', 'medical', 'financial', 'accounting', 'general_offices', 'church'],
    notes: 'Major Tulsa suburb with strong density for professional offices, dental, medical.',
  },
  {
    key: 'jenks',
    name: 'Jenks',
    priority: 7,
    zipCodes: ['74037'],
    bestFor: ['dental', 'medical', 'financial', 'accounting', 'general_offices', 'church', 'retreat'],
    notes: 'High-value south metro suburb. Good for professional offices and event venues.',
  },
  {
    key: 'bixby',
    name: 'Bixby',
    priority: 8,
    zipCodes: ['74008'],
    bestFor: ['dental', 'medical', 'financial', 'accounting', 'general_offices', 'church'],
    notes: 'Growing south metro suburb with good professional office and medical prospects.',
  },
  {
    key: 'glenpool',
    name: 'Glenpool',
    priority: 9,
    zipCodes: ['74033'],
    bestFor: ['dental', 'medical', 'general_offices', 'church'],
    notes: 'Smaller south metro market. Good later-stage territory after Jenks and Bixby.',
  },
  {
    key: 'owasso',
    name: 'Owasso',
    priority: 10,
    zipCodes: ['74055'],
    bestFor: ['dental', 'medical', 'financial', 'accounting', 'general_offices', 'church'],
    notes: 'Important north metro suburb with meaningful commercial market.',
  },
  {
    key: 'collinsville_sperry',
    name: 'Collinsville / Sperry',
    priority: 11,
    zipCodes: ['74021', '74073'],
    bestFor: ['dental', 'medical', 'church', 'general_offices'],
    notes: 'Secondary north metro expansion territory.',
  },
  {
    key: 'sand_springs',
    name: 'Sand Springs',
    priority: 12,
    zipCodes: ['74063'],
    bestFor: ['industrial', 'church', 'general_offices'],
    notes: 'West metro market with industrial, service business, church, and office prospects.',
  },
  {
    key: 'sapulpa',
    name: 'Sapulpa',
    priority: 13,
    zipCodes: ['74066'],
    bestFor: ['industrial', 'church', 'dental', 'medical', 'general_offices'],
    notes: 'Southwest metro market. Useful for churches, local offices, industrial.',
  },
  {
    key: 'catoosa',
    name: 'Catoosa',
    priority: 14,
    zipCodes: ['74015'],
    bestFor: ['industrial', 'manufacturing', 'general_offices'],
    notes: 'Important east metro industrial/logistics market for front-office cleaning.',
  },
]

const DEFAULT_TERRITORY_PRIORITY = [
  'midtown_tulsa',
  'south_tulsa',
  'broken_arrow',
  'jenks',
  'bixby',
  'owasso',
  'downtown_tulsa',
  'glenpool',
  'sand_springs',
  'sapulpa',
  'east_tulsa_industrial',
  'north_west_tulsa',
  'catoosa',
  'collinsville_sperry',
]

export const INDUSTRY_TERRITORY_PRIORITIES: Record<string, string[]> = {
  dental: [
    'midtown_tulsa',
    'south_tulsa',
    'broken_arrow',
    'jenks',
    'bixby',
    'owasso',
    'downtown_tulsa',
    'glenpool',
    'sand_springs',
    'sapulpa',
    'east_tulsa_industrial',
    'north_west_tulsa',
    'catoosa',
    'collinsville_sperry',
  ],
  medical: [
    'south_tulsa',
    'midtown_tulsa',
    'broken_arrow',
    'jenks',
    'bixby',
    'owasso',
    'downtown_tulsa',
    'glenpool',
    'sand_springs',
    'sapulpa',
    'east_tulsa_industrial',
    'north_west_tulsa',
    'catoosa',
    'collinsville_sperry',
  ],
  financial: [
    'midtown_tulsa',
    'south_tulsa',
    'downtown_tulsa',
    'broken_arrow',
    'jenks',
    'bixby',
    'owasso',
    'glenpool',
    'sand_springs',
    'sapulpa',
    'east_tulsa_industrial',
    'north_west_tulsa',
    'catoosa',
    'collinsville_sperry',
  ],
  accounting: [
    'midtown_tulsa',
    'south_tulsa',
    'downtown_tulsa',
    'broken_arrow',
    'jenks',
    'bixby',
    'owasso',
    'glenpool',
    'sand_springs',
    'sapulpa',
    'east_tulsa_industrial',
    'north_west_tulsa',
    'catoosa',
    'collinsville_sperry',
  ],
  law: [
    'downtown_tulsa',
    'midtown_tulsa',
    'south_tulsa',
    'broken_arrow',
    'jenks',
    'bixby',
    'owasso',
    'glenpool',
    'sand_springs',
    'sapulpa',
    'east_tulsa_industrial',
    'north_west_tulsa',
    'catoosa',
    'collinsville_sperry',
  ],
  general_offices: [
    'midtown_tulsa',
    'south_tulsa',
    'broken_arrow',
    'jenks',
    'bixby',
    'owasso',
    'downtown_tulsa',
    'east_tulsa_industrial',
    'glenpool',
    'sand_springs',
    'sapulpa',
    'north_west_tulsa',
    'catoosa',
    'collinsville_sperry',
  ],
  industrial: [
    'east_tulsa_industrial',
    'catoosa',
    'north_west_tulsa',
    'sand_springs',
    'broken_arrow',
    'sapulpa',
    'south_tulsa',
    'glenpool',
    'bixby',
    'owasso',
    'midtown_tulsa',
    'downtown_tulsa',
    'jenks',
    'collinsville_sperry',
  ],
  church: [
    'midtown_tulsa',
    'south_tulsa',
    'broken_arrow',
    'owasso',
    'jenks',
    'bixby',
    'downtown_tulsa',
    'glenpool',
    'sand_springs',
    'sapulpa',
    'north_west_tulsa',
    'east_tulsa_industrial',
    'catoosa',
    'collinsville_sperry',
  ],
  retreat: [
    'downtown_tulsa',
    'jenks',
    'south_tulsa',
    'midtown_tulsa',
    'broken_arrow',
    'owasso',
    'bixby',
    'glenpool',
    'sand_springs',
    'sapulpa',
    'east_tulsa_industrial',
    'north_west_tulsa',
    'catoosa',
    'collinsville_sperry',
  ],
  education: [
    'midtown_tulsa',
    'south_tulsa',
    'broken_arrow',
    'owasso',
    'jenks',
    'bixby',
    'downtown_tulsa',
    'glenpool',
    'sand_springs',
    'sapulpa',
    'north_west_tulsa',
    'east_tulsa_industrial',
    'catoosa',
    'collinsville_sperry',
  ],
}

export function getTerritoryPriority(industryKey: string): string[] {
  return INDUSTRY_TERRITORY_PRIORITIES[industryKey] || DEFAULT_TERRITORY_PRIORITY
}

export function getTerritoriesForIndustry(industryKey: string): Territory[] {
  const priority = getTerritoryPriority(industryKey)
  return priority.map((key) => TULSA_TERRITORIES.find((t) => t.key === key)!).filter(Boolean)
}

export function getTerritoryByKey(key: string): Territory | undefined {
  return TULSA_TERRITORIES.find((t) => t.key === key)
}
